artifacts_root: artifacts

data_ingestion:
  data_ingestion_root: artifacts/data_ingestion
  data_url: https://raw.githubusercontent.com/junaisjunu/proj_dummy_data/main/abalone_train_data.csv
  data_path: artifacts/data_ingestion/data.csv

data_transformation:
  data_transformation_root: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

model_trainer:
  transformed_train_data: artifacts/data_transformation/train.csv
  model_trainer_root: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.pkl
  target: Rings

model_evaluation:
  model_evaluation_root: artifacts/model_evaluation
  model_path: artifacts/model_trainer/model.pkl
  evaluation_score: artifacts/model_evaluation/score.json
  test_data_path: artifacts/data_transformation/test.csv
  target: Rings
  mlflow_uri: 'https://dagshub.com/junaisk456/Abalone_age_prediction.mlflow'

prediction:
  model_path: artifacts/model_trainer/model.pkl

bulk_prediction:
  bulk_prediction_root: artifacts/bulk_prediction
  model_path: artifacts/model_trainer/model.pkl
  result_data: artifacts/bulk_prediction/result_data.csv
